pragma Singleton
import QtQuick
import qs.modules.globals

QtObject {
    property color background: GlobalStates.oledMode ? "#000000" : "#121414"
    property color cursor: "#e3e2e2"
    property color error: "#ffb4ab"
    property color errorContainer: "#93000a"
    property color errorDim: "#ff8678"
    property color errorForeground: "#690005"
    property color foreground: "#e3e2e2"
    property color outline: "#919091"
    property color primary: "#b9c9cf"
    property color primaryForeground: "#243337"
    property color secondary: "#bfc8cb"
    property color secondaryForeground: "#293235"
    property color shadow: "#000000"
    property color surface: "#121414"
    property color surfaceBright: "#38393a"
    property color surfaceContainerHigh: "#292a2a"
    property color surfaceContainerHighest: "#343535"
    property color surfaceContainerLow: "#1b1c1c"
    property color surfaceContainerLowest: "#0d0e0f"
    property color tertiary: "#b2cbd3"
    property color tertiaryForeground: "#1d343a"
    property color red: "#debfc1"
    property color redDim: "#cd9da0"
    property color green: "#bbcabc"
    property color greenDim: "#9eb4a0"
    property color yellow: "#c4c9b1"
    property color yellowDim: "#adb493"
    property color blue: "#c2c6d6"
    property color blueDim: "#a3aac2"
    property color magenta: "#d1c2d2"
    property color magentaDim: "#bba5bc"
    property color cyan: "#b8cacc"
    property color cyanDim: "#9ab4b7"
    property color white: "#b8cacd"
}
