.pragma library

var data = {
    "theme": {
        "oledMode": false,
        "lightMode": false,
        "roundness": 16,
        "font": "Roboto Condensed",
        "fontSize": 14,
        "tintIcons": false,
        "enableCorners": true,
        "animDuration": 300,
        "shadowOpacity": 0.5,
        "shadowColor": "shadow",
        "shadowXOffset": 0,
        "shadowYOffset": 0,
        "shadowBlur": 1,
        "srBg": {
            "gradient": [["background", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "surface",
            "halftoneBackgroundColor": "background",
            "border": ["surfaceBright", 0],
            "itemColor": "overBackground",
            "opacity": 1.0
        },
        "srInternalBg": {
            "gradient": [["background", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "surface",
            "halftoneBackgroundColor": "background",
            "border": ["surfaceBright", 0],
            "itemColor": "overBackground",
            "opacity": 1.0
        },
        "srBarBg": {
            "gradient": [["surfaceDim", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "surface",
            "halftoneBackgroundColor": "surfaceDim",
            "border": ["surfaceBright", 0],
            "itemColor": "overBackground",
            "opacity": 1.0
        },
        "srPane": {
            "gradient": [["surface", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "surfaceBright",
            "halftoneBackgroundColor": "surface",
            "border": ["surfaceBright", 0],
            "itemColor": "overBackground",
            "opacity": 1.0
        },
        "srCommon": {
            "gradient": [["surface", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "background",
            "halftoneBackgroundColor": "surface",
            "border": ["surfaceBright", 0],
            "itemColor": "overBackground",
            "opacity": 1.0
        },
        "srFocus": {
            "gradient": [["surfaceBright", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "surfaceVariant",
            "halftoneBackgroundColor": "surfaceBright",
            "border": ["surfaceBright", 0],
            "itemColor": "overBackground",
            "opacity": 1.0
        },
        "srPrimary": {
            "gradient": [["primary", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "overPrimaryContainer",
            "halftoneBackgroundColor": "primary",
            "border": ["primary", 0],
            "itemColor": "overPrimary",
            "opacity": 1.0
        },
        "srPrimaryFocus": {
            "gradient": [["overPrimaryContainer", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "primary",
            "halftoneBackgroundColor": "overPrimaryContainer",
            "border": ["overBackground", 0],
            "itemColor": "overPrimary",
            "opacity": 1.0
        },
        "srOverPrimary": {
            "gradient": [["overPrimary", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "primaryContainer",
            "halftoneBackgroundColor": "overPrimary",
            "border": ["overPrimary", 0],
            "itemColor": "primary",
            "opacity": 1.0
        },
        "srSecondary": {
            "gradient": [["secondary", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "overSecondaryContainer",
            "halftoneBackgroundColor": "secondary",
            "border": ["secondary", 0],
            "itemColor": "overSecondary",
            "opacity": 1.0
        },
        "srSecondaryFocus": {
            "gradient": [["overSecondaryContainer", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "secondary",
            "halftoneBackgroundColor": "overSecondaryContainer",
            "border": ["overBackground", 0],
            "itemColor": "overSecondary",
            "opacity": 1.0
        },
        "srOverSecondary": {
            "gradient": [["overSecondary", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "secondaryContainer",
            "halftoneBackgroundColor": "overSecondary",
            "border": ["overSecondary", 0],
            "itemColor": "secondary",
            "opacity": 1.0
        },
        "srTertiary": {
            "gradient": [["tertiary", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "overTertiaryContainer",
            "halftoneBackgroundColor": "tertiary",
            "border": ["tertiary", 0],
            "itemColor": "overTertiary",
            "opacity": 1.0
        },
        "srTertiaryFocus": {
            "gradient": [["overTertiaryContainer", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "tertiary",
            "halftoneBackgroundColor": "overTertiaryContainer",
            "border": ["overBackground", 0],
            "itemColor": "overTertiary",
            "opacity": 1.0
        },
        "srOverTertiary": {
            "gradient": [["overTertiary", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "tertiaryContainer",
            "halftoneBackgroundColor": "overTertiary",
            "border": ["overTertiary", 0],
            "itemColor": "tertiary",
            "opacity": 1.0
        },
        "srError": {
            "gradient": [["error", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "overErrorContainer",
            "halftoneBackgroundColor": "error",
            "border": ["error", 0],
            "itemColor": "overError",
            "opacity": 1.0
        },
        "srErrorFocus": {
            "gradient": [["overBackground", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "error",
            "halftoneBackgroundColor": "overErrorContainer",
            "border": ["overBackground", 0],
            "itemColor": "overError",
            "opacity": 1.0
        },
        "srOverError": {
            "gradient": [["overError", 0.0]],
            "gradientType": "linear",
            "gradientAngle": 0,
            "gradientCenterX": 0.5,
            "gradientCenterY": 0.5,
            "halftoneDotMin": 0.0,
            "halftoneDotMax": 2.0,
            "halftoneStart": 0.0,
            "halftoneEnd": 1.0,
            "halftoneDotColor": "errorContainer",
            "halftoneBackgroundColor": "overError",
            "border": ["overError", 0],
            "itemColor": "error",
            "opacity": 1.0
        }
    },
    "bar": {
        "position": "top",
        "launcherIcon": "",
        "launcherIconTint": true,
        "launcherIconFullTint": true,
        "launcherIconSize": 24,
        "showBackground": false,
        "bgOpacity": 0.5,
        "screenList": [],
        "enableFirefoxPlayer": false,
        "barColor": [["surface", 0.0]],
        "barOrientation": "vertical"
    },
    "workspaces": {
        "shown": 10,
        "showAppIcons": true,
        "alwaysShowNumbers": false,
        "showNumbers": false,
        "dynamic": false
    },
    "overview": {
        "rows": 2,
        "columns": 5,
        "scale": 0.1,
        "workspaceSpacing": 4
    },
    "notch": {
        "theme": "default"
    },
    "hyprland": {
        "activeBorderColor": ["primary"],
        "borderAngle": 45,
        "inactiveBorderColor": ["surface"],
        "inactiveBorderAngle": 45,
        "borderSize": 2,
        "rounding": 16,
        "syncRoundness": true,
        "syncBorderWidth": false,
        "syncBorderColor": false,
        "syncShadowOpacity": false,
        "syncShadowColor": false,
        "gapsIn": 2,
        "gapsOut": 4,
        "layout": "dwindle",
        "shadowEnabled": true,
        "shadowRange": 8,
        "shadowRenderPower": 3,
        "shadowSharp": false,
        "shadowIgnoreWindow": true,
        "shadowColor": "shadow",
        "shadowColorInactive": "shadow",
        "shadowOpacity": 0.5,
        "shadowOffset": "0 0",
        "shadowScale": 1.0,
        "blurEnabled": true,
        "blurSize": 4,
        "blurPasses": 2,
        "blurIgnoreOpacity": true,
        "blurNewOptimizations": true,
        "blurXray": false,
        "blurNoise": 0.0,
        "blurContrast": 1.0,
        "blurBrightness": 1.0,
        "blurVibrancy": 0.0,
        "blurVibrancyDarkness": 0.0,
        "blurSpecial": true,
        "blurPopups": false,
        "blurPopupsIgnorealpha": 0.2,
        "blurInputMethods": false,
        "blurInputMethodsIgnorealpha": 0.2
    },
    "performance": {
        "blurTransition": true,
        "windowPreview": true,
        "wavyLine": true
    },
    "weather": {
        "location": "",
        "unit": "C"
    },
    "desktop": {
        "enabled": false,
        "iconSize": 40,
        "spacingVertical": 16,
        "textColor": "overBackground"
    },
    "lockscreen": {
        "position": "bottom"
    },
    "prefix": {
        "clipboard": "cc",
        "emoji": "ee",
        "tmux": "tt",
        "wallpapers": "ww",
        "notes": "nn"
    },
    "system": {
        "disks": ["/"]
    }
}
