pragma Singleton
import QtQuick

QtObject {
    property color background: "{{colors.background.default.hex}}"
    property color cursor: "{{colors.on_background.default.hex}}"
    property color error: "{{colors.error.default.hex}}"
    property color errorContainer: "{{colors.error_container.default.hex}}"
    property color errorDim: "{{colors.error.default.hex | set_lightness: -10.0}}"
    property color errorForeground: "{{colors.on_error.default.hex}}"
    property color foreground: "{{colors.on_background.default.hex}}"
    property color outline: "{{colors.outline.default.hex}}"
    property color primary: "{{colors.primary.default.hex}}"
    property color primaryForeground: "{{colors.on_primary.default.hex}}"
    property color secondary: "{{colors.secondary.default.hex}}"
    property color secondaryForeground: "{{colors.on_secondary.default.hex}}"
    property color shadow: "{{colors.shadow.default.hex}}"
    property color surface: "{{colors.surface.default.hex}}"
    property color surfaceBright: "{{colors.surface_bright.default.hex}}"
    property color surfaceContainerHigh: "{{colors.surface_container_high.default.hex}}"
    property color surfaceContainerHighest: "{{colors.surface_container_highest.default.hex}}"
    property color surfaceContainerLow: "{{colors.surface_container_low.default.hex}}"
    property color surfaceContainerLowest: "{{colors.surface_container_lowest.default.hex}}"
    property color tertiary: "{{colors.tertiary.default.hex}}"
    property color tertiaryForeground: "{{colors.on_tertiary.default.hex}}"
    property color red: "{{colors.red.default.hex}}"
    property color redDim: "{{colors.red.default.hex | set_lightness: -10.0}}"
    property color green: "{{colors.green.default.hex}}"
    property color greenDim: "{{colors.green.default.hex | set_lightness: -10.0}}"
    property color yellow: "{{colors.yellow.default.hex}}"
    property color yellowDim: "{{colors.yellow.default.hex | set_lightness: -10.0}}"
    property color blue: "{{colors.blue.default.hex}}"
    property color blueDim: "{{colors.blue.default.hex | set_lightness: -10.0}}"
    property color magenta: "{{colors.magenta.default.hex}}"
    property color magentaDim: "{{colors.magenta.default.hex | set_lightness: -10.0}}"
    property color cyan: "{{colors.cyan.default.hex}}"
    property color cyanDim: "{{colors.cyan.default.hex | set_lightness: -10.0}}"
    property color white: "{{colors.white.default.hex}}"
}
